config/routes.rb
LGP::Application.routes.draw do

  resources :competencia

  resources :cursos

  resources :empregos

  resources :empresas

  resources :contactos

  resources :noticia

  resources :utilizadors

  get "home/index"
  root :to => "home#index"

  devise_for :utilizadors, :path => "utilizador", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

end

app/models/utilizador.rb
class Utilizador < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :noticium
  has_many :competencium
  has_many :curso
  has_many :emprego
  has_many :contacto
end

app/controllers/utilizadors_controller.rb
#class Utilizadors::RegistationController < Devise::RegistrationsController
class UtilizadorsController < ApplicationController
#class Admins::SessionsController < Devise::SessionsController
  before_action :set_utilizador, only: [:show, :edit, :update, :destroy]



    # GET /utilizadors
  # GET /utilizadors.json
  def index
    @utilizadors = Utilizador.all
  end

  # GET /utilizadors/1
  # GET /utilizadors/1.json
  def show
  end

  # GET /utilizadors/new
  def new
    @utilizador = Utilizador.new
  end

  # GET /utilizadors/1/edit
  def edit
  end

  # POST /utilizadors
  # POST /utilizadors.json
  def create
    @utilizador = Utilizador.new(utilizador_params)

    respond_to do |format|
      if @utilizador.save
        format.html { redirect_to @utilizador, notice: 'Utilizador was successfully created.' }
        format.json { render action: 'show', status: :created, location: @utilizador }
      else
        format.html { render action: 'new' }
        format.json { render json: @utilizador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /utilizadors/1
  # PATCH/PUT /utilizadors/1.json
  def update
    respond_to do |format|
      if @utilizador.update(utilizador_params)
        format.html { redirect_to @utilizador, notice: 'Utilizador was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @utilizador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /utilizadors/1
  # DELETE /utilizadors/1.json
  def destroy
    @utilizador.destroy
    respond_to do |format|
      format.html { redirect_to utilizadors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_utilizador
      @utilizador = Utilizador.find(params[:id])
     # @utilizador = @current_utilizador
      @noticias = @utilizador.noticium
      @competencias = @utilizador.competencium
      @cursos = @utilizador.curso
      @empregos = @utilizador.emprego
      @contactos = @utilizador.contacto
      @contactos_aceites = Array.new
      @contactos.each do |c|
        if c.estado == "Aceite"
          @contactos_aceites.push(c)
        end
      end
      if !(@empregos.size)==0
        @colegas = Empresa.find(@empregos.last.empresa_id).emprego
      end
#      @contactos_colegas = Array.new
#      @contactos_aceites.each do |c|
#        if @empregos.last == Utilizador.find(c.utilizador2_id).emprego.last
#          @contactos_colegas.push(c)
#        end
#      end

    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def utilizador_params
      params.require(:utilizador).permit(:nome, :data_nascimento, :localidade, :email, :telefone)
    end

end

app/helpers/utilizadors_helper.rb
module UtilizadorsHelper
end

app/views/utilizadors/_form.html.erb
<%= form_for(@utilizador) do |f| %>
  <% if @utilizador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@utilizador.errors.count, "error") %> prohibited this utilizador from being saved:</h2>

      <ul>
      <% @utilizador.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :data_nascimento %><br>
    <%= f.datetime_select :data_nascimento %>
  </div>
  <div class="field">
    <%= f.label :localidade %><br>
    <%= f.text_field :localidade %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
    <div class="field">
      <%= f.label :password_confirmation %><br>
      <%= f.text_field :password_confirmation %>
    </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.number_field :telefone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/utilizadors/edit.html.erb
<h1>Editing utilizador</h1>

<%= render 'form' %>

<%= link_to 'Show', @utilizador %> |
<%= link_to 'Back', utilizadors_path %>

app/views/utilizadors/index.html.erb
<h1>Listing utilizadors</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Data nascimento</th>
      <th>Localidade</th>
      <th>Email</th>
      <th>Telefone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @utilizadors.each do |utilizador| %>
      <tr>
        <td><%= utilizador.nome %></td>
        <td><%= utilizador.data_nascimento %></td>
        <td><%= utilizador.localidade %></td>
        <td><%= utilizador.email %></td>
        <td><%= utilizador.telefone %></td>
        <td><%= link_to 'Show', utilizador %></td>
        <td><%= link_to 'Edit', edit_utilizador_path(utilizador) %></td>
        <td><%= link_to 'Destroy', utilizador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Utilizador', new_utilizador_path %>

app/views/utilizadors/new.html.erb
<h1>New utilizador</h1>

<%= render 'form' %>

<%= link_to 'Back', utilizadors_path %>

app/views/utilizadors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @utilizador.nome %>
</p>

<p>
  <strong>Data nascimento:</strong>
  <%= @utilizador.data_nascimento %>
</p>

<p>
  <strong>Localidade:</strong>
  <%= @utilizador.localidade %>
</p>

<p>
  <strong>Email:</strong>
  <%= @utilizador.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @utilizador.telefone %>
</p>
<hr>
    <strong>Competencias:</strong>
    <% @competencias.each do |c| %>
        <p>- <%= c.nome %> </p>
    <% end %>
<p><%= link_to 'Nova competencia', new_competencium_path(:utilizador_id => @utilizador.id) %> </p>
<hr>

<strong>Cursos:</strong>
<ul>
<% @cursos.each do |c| %>
    <li><b> <%= c.nome %> </b> - <%= c.univ %> - <%= c.ano %> </li>
<% end %>
</ul>
<p><%= link_to 'Novo curso', new_curso_path(:utilizador_id => @utilizador.id) %> </p>
<hr>

<strong>Noticias:</strong>
<% @noticias.each do |n| %>
    <h3> <%= link_to n.titulo, n %> </h3>
    <p>- <%= n.texto %> </p>
    <p>- <%= n.img %> </p>
<% end %>
<p><%= link_to 'Nova noticia', new_noticium_path(:utilizador_id => @utilizador.id) %> </p>
<hr>

<strong>Empregos</strong>
<% @empregos.each do |e| %>
    <p><b> <%= link_to Empresa.find(e.empresa_id).nome, Empresa.find(e.empresa_id) %> </b>
    - <%= e.cargo %> - <%= e.data_entrada %> // <%= e.data_saida %> </p>
<% end %>
<p><%= link_to 'Novo Emprego', new_emprego_path(:utilizador_id => @utilizador.id) %> </p>
<hr>

<strong>Contactos</strong>
<%if @contactos_aceites.size==0 %>
    <p>De momento não tem nenhum contacto na sua rede! Adicione <%= link_to "contactos", utilizadors_path %>!</p>
<% else %>
    <% @contactos_aceites.each do |c| %>
        <p><b> <%= link_to Utilizador.find(c.utilizador2_id).nome, Utilizador.find(c.utilizador2_id) %> </b>
          - <%= c.estado %>  </p>
    <% end %>
<% end %>
<hr>

<strong>Colegas</strong>
<%if @empregos.size==0 #TODO ADICIONAR CONDICAO PARA CONFIRMAR SE TEM COLEGAS%>
    <p>De momento não tem nenhum emprego! Edite o seu <%= link_to "perfil", edit_utilizador_registration_path %>!</p>
<% else %>
    <%if Empresa.find(@empregos.last.empresa_id).emprego.size==1 #TODO ADICIONAR CONDICAO PARA CONFIRMAR SE TEM COLEGAS%>
        <p>A sua empresa actual não tem funcionários</p>
    <% else %>
                            <%  #TODO CODIGO COPIADO PARA BLOCO %>
    <% end %>
<% end %>
<hr>
<hr>




<%= link_to 'Edit', edit_utilizador_path(@utilizador) %> |
<%= link_to 'Back', utilizadors_path %>