config/routes.rb
LGP::Application.routes.draw do

  resources :competencia

  resources :cursos

  resources :empregos

  resources :empresas

  resources :contactos

  resources :noticia

  resources :utilizadors

  get "home/index"
  root :to => "home#index"

  devise_for :utilizadors, :path => "utilizador", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  has_many :emprego
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  before_action :set_empresa, only: [:show, :edit, :update, :destroy]

  # GET /empresas
  # GET /empresas.json
  def index
    @empresas = Empresa.all
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
  end

  # GET /empresas/new
  def new
    @empresa = Empresa.new
  end

  # GET /empresas/1/edit
  def edit
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(empresa_params)

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        format.json { render action: 'show', status: :created, location: @empresa }
      else
        format.html { render action: 'new' }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empresas/1
  # PATCH/PUT /empresas/1.json
  def update
    respond_to do |format|
      if @empresa.update(empresa_params)
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa.destroy
    respond_to do |format|
      format.html { redirect_to empresas_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_empresa
      @empresa = Empresa.find(params[:id])
      @empregados = @empresa.emprego
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def empresa_params
      params.require(:empresa).permit(:nome, :historia, :data_criacao, :email, :telefone, :morada, :areas, :projectos, :admin_id)
    end
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/_form.html.erb
<%= form_for(@empresa) do |f| %>
  <% if @empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
      <% @empresa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :historia %><br>
    <%= f.text_field :historia %>
  </div>
  <div class="field">
    <%= f.label :data_criacao %><br>
    <%= f.datetime_select :data_criacao %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br>
    <%= f.number_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :morada %><br>
    <%= f.text_field :morada %>
  </div>
  <div class="field">
    <%= f.label :areas %><br>
    <%= f.text_field :areas %>
  </div>
  <div class="field">
    <%= f.label :projectos %><br>
    <%= f.text_field :projectos %>
  </div>
  <div class="field">
    <%= f.label :admin_id %><br>
    <%= f.number_field :admin_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1>Editing empresa</h1>

<%= render 'form' %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/index.html.erb
<h1>Listing empresas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Historia</th>
      <th>Data criacao</th>
      <th>Email</th>
      <th>Telefone</th>
      <th>Morada</th>
      <th>Areas</th>
      <th>Projectos</th>
      <th>Admin</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @empresas.each do |empresa| %>
      <tr>
        <td><%= empresa.nome %></td>
        <td><%= empresa.historia %></td>
        <td><%= empresa.data_criacao %></td>
        <td><%= empresa.email %></td>
        <td><%= empresa.telefone %></td>
        <td><%= empresa.morada %></td>
        <td><%= empresa.areas %></td>
        <td><%= empresa.projectos %></td>
        <td><%= empresa.admin_id %></td>
        <td><%= link_to 'Show', empresa %></td>
        <td><%= link_to 'Edit', edit_empresa_path(empresa) %></td>
        <td><%= link_to 'Destroy', empresa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Empresa', new_empresa_path %>

app/views/empresas/new.html.erb
<h1>New empresa</h1>

<%= render 'form' %>

<%= link_to 'Back', empresas_path %>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @empresa.nome %>
</p>

<p>
  <strong>Historia:</strong>
  <%= @empresa.historia %>
</p>

<p>
  <strong>Data criacao:</strong>
  <%= @empresa.data_criacao %>
</p>

<p>
  <strong>Email:</strong>
  <%= @empresa.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @empresa.telefone %>
</p>

<p>
  <strong>Morada:</strong>
  <%= @empresa.morada %>
</p>

<p>
  <strong>Areas:</strong>
  <%= @empresa.areas %>
</p>

<p>
  <strong>Projectos:</strong>
  <%= @empresa.projectos %>
</p>

<p>
  <strong>Admin:</strong>
  <%= @empresa.admin_id %>
</p>


<strong>Empregados</strong>
<% @empregados.each do |e| %>
    <p><b> <%= link_to Utilizador.find(e.utilizador_id).nome, Utilizador.find(e.utilizador_id) %> </b>
      - <%= e.cargo %> - <%= e.data_entrada %> // <%= e.data_saida %> </p>
<% end %>
<p><%= link_to 'Novo Emprego', new_emprego_path(:utilizador_id => @empresa.id) %> </p>
<hr>
<hr>


<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>