config/routes.rb
LGP::Application.routes.draw do

  resources :competencia

  resources :cursos

  resources :empregos

  resources :empresas

  resources :contactos

  resources :noticia

  resources :utilizadors

  get "home/index"
  root :to => "home#index"

  devise_for :utilizadors, :path => "utilizador", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

end

app/models/competencium.rb
class Competencium < ActiveRecord::Base
  belongs_to :utilizador
end

app/models/contacto.rb
class Contacto < ActiveRecord::Base
  belongs_to :utilizador
end

app/models/curso.rb
class Curso < ActiveRecord::Base
  belongs_to :utilizador
end

app/models/emprego.rb
class Emprego < ActiveRecord::Base
  belongs_to :utilizador
  belongs_to :empresa
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  has_many :emprego
end

app/models/noticium.rb
class Noticium < ActiveRecord::Base
  belongs_to :utilizador
end

app/models/utilizador.rb
class Utilizador < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :noticium
  has_many :competencium
  has_many :curso
  has_many :emprego
  has_many :contacto
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :set_curso, only: [:show, :edit, :update, :destroy]

  # GET /cursos
  # GET /cursos.json
  def index
    @cursos = Curso.all
  end

  # GET /cursos/1
  # GET /cursos/1.json
  def show
  end

  # GET /cursos/new
  def new
    if params.has_key? :utilizador_id
      @curso = Curso.new(:utilizador_id => params[:utilizador_id])
    else
      @curso = Curso.new
    end
  end

  # GET /cursos/1/edit
  def edit
  end

  # POST /cursos
  # POST /cursos.json
  def create
    @curso = Curso.new(curso_params)

    respond_to do |format|
      if @curso.save
        format.html { redirect_to @curso, notice: 'Curso was successfully created.' }
        format.json { render action: 'show', status: :created, location: @curso }
      else
        format.html { render action: 'new' }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1
  # PATCH/PUT /cursos/1.json
  def update
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to @curso, notice: 'Curso was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1
  # DELETE /cursos/1.json
  def destroy
    @curso.destroy
    respond_to do |format|
      format.html { redirect_to cursos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def curso_params
      params.require(:curso).permit(:utilizador_id, :nome, :univ, :ano)
    end
end

app/controllers/empregos_controller.rb
class EmpregosController < ApplicationController
  before_action :set_emprego, only: [:show, :edit, :update, :destroy]

  # GET /empregos
  # GET /empregos.json
  def index
    @empregos = Emprego.all
  end

  # GET /empregos/1
  # GET /empregos/1.json
  def show
  end

  # GET /empregos/new
  def new
    @emprego = Emprego.new
  end

  # GET /empregos/1/edit
  def edit
  end

  # POST /empregos
  # POST /empregos.json
  def create
    @emprego = Emprego.new(emprego_params)

    respond_to do |format|
      if @emprego.save
        format.html { redirect_to @emprego, notice: 'Emprego was successfully created.' }
        format.json { render action: 'show', status: :created, location: @emprego }
      else
        format.html { render action: 'new' }
        format.json { render json: @emprego.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /empregos/1
  # PATCH/PUT /empregos/1.json
  def update
    respond_to do |format|
      if @emprego.update(emprego_params)
        format.html { redirect_to @emprego, notice: 'Emprego was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @emprego.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empregos/1
  # DELETE /empregos/1.json
  def destroy
    @emprego.destroy
    respond_to do |format|
      format.html { redirect_to empregos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emprego
      @emprego = Emprego.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emprego_params
      params.require(:emprego).permit(:utilizador_id, :empresa_id, :cargo, :data_entrada, :data_saida)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/noticia_controller.rb
class NoticiaController < ApplicationController
  before_action :set_noticium, only: [:show, :edit, :update, :destroy]

  # GET /noticia
  # GET /noticia.json
  def index
    @noticia = Noticium.all
  end

  # GET /noticia/1
  # GET /noticia/1.json
  def show
  end

  # GET /noticia/new
  def new
    if params.has_key? :utilizador_id
      @noticium = Noticium.new(:utilizador_id => params[:utilizador_id])
    else
      @noticium = Noticium.new
    end
  end

  # GET /noticia/1/edit
  def edit
  end

  # POST /noticia
  # POST /noticia.json
  def create
    @noticium = Noticium.new(noticium_params)

    respond_to do |format|
      if @noticium.save
        format.html { redirect_to @noticium, notice: 'Noticium was successfully created.' }
        format.json { render action: 'show', status: :created, location: @noticium }
      else
        format.html { render action: 'new' }
        format.json { render json: @noticium.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noticia/1
  # PATCH/PUT /noticia/1.json
  def update
    respond_to do |format|
      if @noticium.update(noticium_params)
        format.html { redirect_to @noticium, notice: 'Noticium was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @noticium.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noticia/1
  # DELETE /noticia/1.json
  def destroy
    @noticium.destroy
    respond_to do |format|
      format.html { redirect_to noticia_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noticium
      @noticium = Noticium.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def noticium_params
      params.require(:noticium).permit(:utilizador_id, :img, :texto, :titulo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competencia_helper.rb
module CompetenciaHelper
end

app/helpers/contactos_helper.rb
module ContactosHelper
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/helpers/empregos_helper.rb
module EmpregosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/noticia_helper.rb
module NoticiaHelper
end

app/helpers/utilizadors_helper.rb
module UtilizadorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Let's get Pro! - Home</title>
  <link rel="shortcut icon" href="/images/icon.ico">
  <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.10.2.min.js"></script>

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
 <!-- <%=  javascript_include_tag "application", "data-turbolinks-track" => true %> -->
  <%= javascript_include_tag "js", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body >
<div id="secondBackground">

  <!-- HEADER-->
  <div id="header" >
    <div id="leftHeader">
      <%= link_to "<img src='/images/banner_grey.png'  alt='Logo' />".html_safe, root_url %>
    </div>
    <div id="rightHeader">


      <p class="navbar-text pull-right">
        <% if utilizador_signed_in? %>
            <h1 class="textColorTop"><%= link_to current_utilizador.nome, utilizador_path(current_utilizador) %>!</h1>
            <%= link_to 'Edit profile', edit_utilizador_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_utilizador_session_path, method: :delete, :class => 'navbar-link'  %>
            <%= javascript_include_tag :defaults %>
            <%= link_to "Sign out", destroy_utilizador_session_path, :method => :delete, :class => 'navbar-link'%>
        <% else %>
            <h1 class="textColorTop">Bem vindo!</h1>
            <%= link_to "Sign up", new_utilizador_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_utilizador_session_path, :class => 'navbar-link'  %>
        <% end %>

        <br>
        <% if notice %>
            <p class="alert alert-notice"><%= notice %></p>
        <% end %>
        <% if alert %>
            <p class="alert alert-error"><%= alert %></p>
        <% end %>

        </div>
  </div>
  <!-- FIM-HEADER-->

  <div id="menu">
    <ul id="nav">
      <% if utilizador_signed_in? %>
          <li><img src="/images/home.png" width="20"><%= link_to "Página inicial", root_url %></li>
          <li class="hasChild"><img src="/images/profile.png" width="20"><a id="pagLink"> As minhas páginas</a>
            <ul style="display: none;">
              <li><img src="/images/profile2.png" width="15"><%=link_to  "O meu perfil", utilizador_path(current_utilizador)%></li>
              <li><img src="/images/profile_empresa.png" width="20"><a href="ProfileEmpresa.html">A minha empresa</a></li>
            </ul>
          </li>
          <li><img src="/images/Suitcase_icon.png" width="18"> <%= link_to "Empresas", empresas_path%> </li>
          <li><img src="/images/friends.png" width="18"> <%= link_to "Contactos", utilizadors_path%> </li>
          <!-- <%= link_to '<li><img src="/images/friends.png" width="18"> Contactos </li>'.html_safe, utilizadors_path%> -->
          <li><img src="/images/lupa.png" width="18"><a href="Pesquisa.html"> Pesquisa</a> </li>
          <li></li>
      <%else #TODO Que menu se mete aqui? %>

      <%end%>
    </ul>

  </div>


  <%= yield %>






  <div id="feed">
    <p id="feedTitle">Feed de notícias</p><img src="/images/feed.png" width="30">
    <hr>
    <p id="headerNews">O Lorem Ipsum</p>
    <p id="newsText">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
    <hr>
    <p id="headerNews">Rick Roll - Lyrics</p>
    <p id="newsText">Never gonna give you up<br>
      Never gonna let you down<br>
      Never gonna run around and desert you<br>
      Never gonna make you cry <br>
      Never gonna say goodbye<br>
      Never gonna tell a lie and hurt you
    </p>
    <hr>
  </div>
  <!-- FOOTER -->
  <div id="footer" >
    João Campos e Tiago Daniel  ||
    <a href="About us" class="aboutus">Sobre nós</a>
  </div>
  <!-- FIM-FOOTER -->
</div>
<p class="flag" ><a href="http://ctp.di.fct.unl.pt/lei/daweb/">ProjDAWeb</a></p>



<br>

| <%= link_to 'Utilizadores', utilizadors_path %>
| <%= link_to 'Empresas', empresas_path %>


</body>
</html>